name: movie_salah_yaaqba
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  connectivity_plus: ^6.1.3
  flutter_screenutil: ^5.9.3
  flutter_vector_icons: ^2.0.0
  vibration: ^3.1.3
  glowy_borders: ^1.0.2
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  lottie: ^3.3.1
  responsive_framework: ^1.5.1
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  http: ^1.3.0
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  path: ^1.9.1
  sqflite: ^2.4.2
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_icons:
  android: "launcher_icon"  # Generate icons for Android
  ios: true                 # Generate icons for iOS
  image_path: "assets/images/nabeeh_movie.png"
flutter_native_splash:
  android: true
  ios: true
  color: "#FfFfFf"  # Replace with your desired color
  image: "assets/images/nabeeh_movie.png"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy/Chewy-Regular.ttf

    - family: Vollkorn
      fonts:
        - asset: assets/fonts/Vollkorn/Vollkorn-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Vollkorn/Vollkorn-VariableFont_wght.ttf

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/static/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-VariableFont_wght.ttf
          weight: 400
    - family: CrimsonText
      fonts:
        - asset: assets/fonts/Crimson/CrimsonText-Bold.ttf
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lottie/

